// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_main_screen_init(void)
{
ui_main = lv_obj_create(NULL);
lv_obj_remove_flag( ui_main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_panel_bottomline = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_panel_bottomline, 1200);
lv_obj_set_height( ui_main_panel_bottomline, 6);
lv_obj_set_x( ui_main_panel_bottomline, 0 );
lv_obj_set_y( ui_main_panel_bottomline, 300 );
lv_obj_set_align( ui_main_panel_bottomline, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_main_panel_bottomline, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_main_panel_bottomline, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_panel_bottomline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_label_label1 = lv_label_create(ui_main);
lv_obj_set_width( ui_main_label_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_label_label1, 550 );
lv_obj_set_y( ui_main_label_label1, 330 );
lv_obj_set_align( ui_main_label_label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_label_label1,"12:00");
lv_obj_set_style_text_font(ui_main_label_label1, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_image_image4 = lv_image_create(ui_main);
lv_image_set_src(ui_main_image_image4, &ui_img_a_png);
lv_obj_set_width( ui_main_image_image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image4, 374 );
lv_obj_set_y( ui_main_image_image4, 330 );
lv_obj_set_align( ui_main_image_image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_image_image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_main_image_image4,110);

ui_main_image_image1 = lv_image_create(ui_main);
lv_image_set_src(ui_main_image_image1, &ui_img_b_png);
lv_obj_set_width( ui_main_image_image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image1, 252 );
lv_obj_set_y( ui_main_image_image1, 330 );
lv_obj_set_align( ui_main_image_image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_image_image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_main_image_image1,110);

ui_main_label_label2 = lv_label_create(ui_main);
lv_obj_set_width( ui_main_label_label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_label_label2, 432 );
lv_obj_set_y( ui_main_label_label2, 330 );
lv_obj_set_align( ui_main_label_label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_label_label2,"Install");
lv_obj_set_style_text_font(ui_main_label_label2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_label_label3 = lv_label_create(ui_main);
lv_obj_set_width( ui_main_label_label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_label_label3, 297 );
lv_obj_set_y( ui_main_label_label3, 330 );
lv_obj_set_align( ui_main_label_label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_label_label3,"Info");
lv_obj_set_style_text_font(ui_main_label_label3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_panel_panel1 = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_panel_panel1, 1135);
lv_obj_set_height( ui_main_panel_panel1, 625);
lv_obj_set_x( ui_main_panel_panel1, 63 );
lv_obj_set_y( ui_main_panel_panel1, -35 );
lv_obj_set_align( ui_main_panel_panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_main_panel_panel1, LV_OBJ_FLAG_SCROLL_ELASTIC );    /// Flags
lv_obj_set_style_bg_color(ui_main_panel_panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_panel_panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_main_panel_panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_image_image3 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image3, &ui_img_30e1e5aed207066f1b8acb2c7d2a3e532b3d8707615c58e40635bc5d84377ce3_png);
lv_obj_set_width( ui_main_image_image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image3, LV_SIZE_CONTENT);   /// 1
lv_obj_add_flag( ui_main_image_image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image5 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image5, &ui_img_29c1ff1b697b468082d43540425fca8f538865a8d1f876de46ae5490203b6c2e_png);
lv_obj_set_width( ui_main_image_image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image5, 270 );
lv_obj_set_y( ui_main_image_image5, 0 );
lv_obj_add_flag( ui_main_image_image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image6 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image6, &ui_img_399bd3a4f656457bb63e921378eb701908298c8f2b2ad3193c437c206da97681_png);
lv_obj_set_width( ui_main_image_image6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image6, 540 );
lv_obj_set_y( ui_main_image_image6, 0 );
lv_obj_add_flag( ui_main_image_image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image7 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image7, &ui_img_3c3011e367e82258bbd36283bfe89d7292e6f44792bda005da3b964cd6388013_png);
lv_obj_set_width( ui_main_image_image7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image7, 810 );
lv_obj_set_y( ui_main_image_image7, 0 );
lv_obj_add_flag( ui_main_image_image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image8 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image8, &ui_img_4b53da7ca4b118fe37c8b8040609b84dc63214d6131c51592486de9bf29ef29c_png);
lv_obj_set_width( ui_main_image_image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image8, 0 );
lv_obj_set_y( ui_main_image_image8, 270 );
lv_obj_add_flag( ui_main_image_image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image9 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image9, &ui_img_4ffe57aabf1b6a2bf19cab0139a8bb4f99d14ef2f0031f83acd0f28810f66dbf_png);
lv_obj_set_width( ui_main_image_image9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image9, 270 );
lv_obj_set_y( ui_main_image_image9, 270 );
lv_obj_add_flag( ui_main_image_image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image10 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image10, &ui_img_628f3436b87a02061bf9014ee7949fc379564c75364e66dca290fb1e54e9c095_png);
lv_obj_set_width( ui_main_image_image10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image10, 540 );
lv_obj_set_y( ui_main_image_image10, 270 );
lv_obj_add_flag( ui_main_image_image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image11 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image11, &ui_img_66b639f88213ebf50af4a9eaca2da8c64a24a7314a0c80d587fec466df74d8b9_png);
lv_obj_set_width( ui_main_image_image11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image11, 810 );
lv_obj_set_y( ui_main_image_image11, 270 );
lv_obj_add_flag( ui_main_image_image11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image2 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image2, &ui_img_7f4d41bf9dbc8f7379e2f7530b8e969220dfdc933506ec8eaab7085267533a50_png);
lv_obj_set_width( ui_main_image_image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image2, 0 );
lv_obj_set_y( ui_main_image_image2, 540 );
lv_obj_add_flag( ui_main_image_image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image12 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image12, &ui_img_9743b1bb18f8b7e40947a037557131be402985046b4e57f7c2c4796abe024b30_png);
lv_obj_set_width( ui_main_image_image12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image12, 270 );
lv_obj_set_y( ui_main_image_image12, 540 );
lv_obj_add_flag( ui_main_image_image12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image13 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image13, &ui_img_ad4d31f664a1ce704f0219da2805f8459595bc3c01c3f04df2e32ba34a05b8c6_png);
lv_obj_set_width( ui_main_image_image13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image13, 540 );
lv_obj_set_y( ui_main_image_image13, 540 );
lv_obj_add_flag( ui_main_image_image13, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image14 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image14, &ui_img_aeab72bcb6fb6c79c32bddec987764f6e47c3e90cd32642a84de75f631b4eed0_png);
lv_obj_set_width( ui_main_image_image14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image14, 810 );
lv_obj_set_y( ui_main_image_image14, 540 );
lv_obj_add_flag( ui_main_image_image14, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image15 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image15, &ui_img_b7c8b605f109a0f090fd4231a33c87eaf91ff1bb3a1b6fe94b9057a822162a6d_png);
lv_obj_set_width( ui_main_image_image15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image15, 0 );
lv_obj_set_y( ui_main_image_image15, 810 );
lv_obj_add_flag( ui_main_image_image15, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image16 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image16, &ui_img_bfeb5333a4473854d4cba8332d64152d595879c3714e687b45c47ad33b234a08_png);
lv_obj_set_width( ui_main_image_image16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image16, 270 );
lv_obj_set_y( ui_main_image_image16, 810 );
lv_obj_add_flag( ui_main_image_image16, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image17 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image17, &ui_img_d3c210e61e8487200fc4c344987243a60257838187a69a6a81c42d7447d5d192_png);
lv_obj_set_width( ui_main_image_image17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image17, 540 );
lv_obj_set_y( ui_main_image_image17, 810 );
lv_obj_add_flag( ui_main_image_image17, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_image_image18 = lv_image_create(ui_main_panel_panel1);
lv_image_set_src(ui_main_image_image18, &ui_img_f9dc003e469d3986eb0f7b6d972629ef201946028d530ac946823886e22ca3b2_png);
lv_obj_set_width( ui_main_image_image18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_image_image18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_image_image18, 810 );
lv_obj_set_y( ui_main_image_image18, 810 );
lv_obj_add_flag( ui_main_image_image18, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_main_image_image18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_container_container1 = lv_obj_create(ui_main);
lv_obj_remove_style_all(ui_main_container_container1);
lv_obj_set_width( ui_main_container_container1, 100);
lv_obj_set_height( ui_main_container_container1, 50);
lv_obj_set_align( ui_main_container_container1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_main_container_container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags


}
