// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_main_screen_init(void)
{
ui_main = lv_obj_create(NULL);
lv_obj_remove_flag( ui_main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_panel_panelpopup = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_panel_panelpopup, 442);
lv_obj_set_height( ui_main_panel_panelpopup, 163);
lv_obj_set_align( ui_main_panel_panelpopup, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_panel_panelpopup, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_main_panel_panelpopup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_label_label12 = lv_label_create(ui_main_panel_panelpopup);
lv_obj_set_width( ui_main_label_label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_label_label12, 1 );
lv_obj_set_y( ui_main_label_label12, -38 );
lv_obj_set_align( ui_main_label_label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_label_label12,"Install application?");
lv_obj_set_style_text_font(ui_main_label_label12, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_button_button6 = lv_button_create(ui_main_panel_panelpopup);
lv_obj_set_width( ui_main_button_button6, 100);
lv_obj_set_height( ui_main_button_button6, 50);
lv_obj_set_x( ui_main_button_button6, -120 );
lv_obj_set_y( ui_main_button_button6, 33 );
lv_obj_set_align( ui_main_button_button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_button_button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_main_button_button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_main_button_button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_button_button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_label_label9 = lv_label_create(ui_main_button_button6);
lv_obj_set_width( ui_main_label_label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_main_label_label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_label_label9,"YES");
lv_obj_set_style_text_color(ui_main_label_label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_main_label_label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_main_label_label9, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_button_button4 = lv_button_create(ui_main_panel_panelpopup);
lv_obj_set_width( ui_main_button_button4, 100);
lv_obj_set_height( ui_main_button_button4, 50);
lv_obj_set_x( ui_main_button_button4, 120 );
lv_obj_set_y( ui_main_button_button4, 33 );
lv_obj_set_align( ui_main_button_button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_button_button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_main_button_button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_main_button_button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_button_button4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_label_label10 = lv_label_create(ui_main_button_button4);
lv_obj_set_width( ui_main_label_label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_main_label_label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_label_label10,"NO");
lv_obj_set_style_text_color(ui_main_label_label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_main_label_label10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_main_label_label10, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_panel_panel1 = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_panel_panel1, 1135);
lv_obj_set_height( ui_main_panel_panel1, 625);
lv_obj_set_x( ui_main_panel_panel1, 63 );
lv_obj_set_y( ui_main_panel_panel1, -35 );
lv_obj_set_align( ui_main_panel_panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_main_panel_panel1, LV_OBJ_FLAG_SCROLL_ELASTIC );    /// Flags
lv_obj_set_scrollbar_mode(ui_main_panel_panel1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_main_panel_panel1, LV_DIR_VER);
lv_obj_set_style_bg_color(ui_main_panel_panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_panel_panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_main_panel_panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_imgbutton_imgbutton4 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_29c1ff1b697b468082d43540425fca8f538865a8d1f876de46ae5490203b6c2e_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton4, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton4, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton4, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton4, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton4, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton4, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton4, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton4, 0 );
lv_obj_set_y( ui_main_imgbutton_imgbutton4, 2 );

ui_main_imgbutton_imgbutton5 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton5, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_30e1e5aed207066f1b8acb2c7d2a3e532b3d8707615c58e40635bc5d84377ce3_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton5, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton5, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton5, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton5, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton5, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton5, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton5, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton5, 270 );
lv_obj_set_y( ui_main_imgbutton_imgbutton5, 0 );

ui_main_imgbutton_imgbutton6 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton6, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_399bd3a4f656457bb63e921378eb701908298c8f2b2ad3193c437c206da97681_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton6, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton6, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton6, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton6, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton6, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton6, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton6, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton6, 540 );
lv_obj_set_y( ui_main_imgbutton_imgbutton6, 0 );

ui_main_imgbutton_imgbutton7 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton7, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_3c3011e367e82258bbd36283bfe89d7292e6f44792bda005da3b964cd6388013_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton7, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton7, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton7, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton7, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton7, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton7, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton7, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton7, 810 );
lv_obj_set_y( ui_main_imgbutton_imgbutton7, 0 );

ui_main_imgbutton_imgbutton8 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton8, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_4b53da7ca4b118fe37c8b8040609b84dc63214d6131c51592486de9bf29ef29c_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton8, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton8, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton8, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton8, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton8, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton8, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton8, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton8, 0 );
lv_obj_set_y( ui_main_imgbutton_imgbutton8, 270 );

ui_main_imgbutton_imgbutton9 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton9, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_4ffe57aabf1b6a2bf19cab0139a8bb4f99d14ef2f0031f83acd0f28810f66dbf_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton9, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton9, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton9, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton9, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton9, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton9, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton9, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton9, 270 );
lv_obj_set_y( ui_main_imgbutton_imgbutton9, 270 );

ui_main_imgbutton_imgbutton10 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton10, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_628f3436b87a02061bf9014ee7949fc379564c75364e66dca290fb1e54e9c095_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton10, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton10, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton10, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton10, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton10, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton10, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton10, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton10, 540 );
lv_obj_set_y( ui_main_imgbutton_imgbutton10, 270 );

ui_main_imgbutton_imgbutton11 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton11, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_66b639f88213ebf50af4a9eaca2da8c64a24a7314a0c80d587fec466df74d8b9_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton11, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton11, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton11, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton11, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton11, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton11, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton11, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton11, 810 );
lv_obj_set_y( ui_main_imgbutton_imgbutton11, 270 );

ui_main_imgbutton_imgbutton12 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton12, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_7f4d41bf9dbc8f7379e2f7530b8e969220dfdc933506ec8eaab7085267533a50_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton12, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton12, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton12, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton12, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton12, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton12, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton12, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton12, 0 );
lv_obj_set_y( ui_main_imgbutton_imgbutton12, 540 );

ui_main_imgbutton_imgbutton13 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton13, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_9743b1bb18f8b7e40947a037557131be402985046b4e57f7c2c4796abe024b30_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton13, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton13, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton13, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton13, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton13, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton13, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton13, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton13, 270 );
lv_obj_set_y( ui_main_imgbutton_imgbutton13, 540 );

ui_main_imgbutton_imgbutton14 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton14, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_ad4d31f664a1ce704f0219da2805f8459595bc3c01c3f04df2e32ba34a05b8c6_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton14, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton14, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton14, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton14, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton14, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton14, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton14, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton14, 540 );
lv_obj_set_y( ui_main_imgbutton_imgbutton14, 540 );

ui_main_imgbutton_imgbutton15 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton15, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_aeab72bcb6fb6c79c32bddec987764f6e47c3e90cd32642a84de75f631b4eed0_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton15, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton15, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton15, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton15, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton15, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton15, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton15, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton15, 810 );
lv_obj_set_y( ui_main_imgbutton_imgbutton15, 540 );

ui_main_imgbutton_imgbutton16 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton16, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_b7c8b605f109a0f090fd4231a33c87eaf91ff1bb3a1b6fe94b9057a822162a6d_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton16, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton16, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton16, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton16, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton16, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton16, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton16, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton16, 0 );
lv_obj_set_y( ui_main_imgbutton_imgbutton16, 810 );

ui_main_imgbutton_imgbutton17 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton17, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_bfeb5333a4473854d4cba8332d64152d595879c3714e687b45c47ad33b234a08_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton17, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton17, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton17, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton17, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton17, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton17, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton17, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton17, 270 );
lv_obj_set_y( ui_main_imgbutton_imgbutton17, 810 );

ui_main_imgbutton_imgbutton18 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton18, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_d3c210e61e8487200fc4c344987243a60257838187a69a6a81c42d7447d5d192_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton18, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton18, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton18, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton18, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton18, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton18, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton18, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton18, 540 );
lv_obj_set_y( ui_main_imgbutton_imgbutton18, 810 );

ui_main_imgbutton_imgbutton19 = lv_imagebutton_create(ui_main_panel_panel1);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton19, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_f9dc003e469d3986eb0f7b6d972629ef201946028d530ac946823886e22ca3b2_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton19, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton19, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton19, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton19, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton19, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_width( ui_main_imgbutton_imgbutton19, 256);
lv_obj_set_height( ui_main_imgbutton_imgbutton19, 256);
lv_obj_set_x( ui_main_imgbutton_imgbutton19, 810 );
lv_obj_set_y( ui_main_imgbutton_imgbutton19, 810 );

ui_main_panel_bottomline = lv_obj_create(ui_main);
lv_obj_set_width( ui_main_panel_bottomline, 1200);
lv_obj_set_height( ui_main_panel_bottomline, 6);
lv_obj_set_x( ui_main_panel_bottomline, 0 );
lv_obj_set_y( ui_main_panel_bottomline, 300 );
lv_obj_set_align( ui_main_panel_bottomline, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_main_panel_bottomline, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_main_panel_bottomline, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_panel_bottomline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_imgbutton_imgbutton3 = lv_imagebutton_create(ui_main);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_dark_theme_plus_button_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton3, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton3, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton3, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton3, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton3, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_main_imgbutton_imgbutton3, 32);
lv_obj_set_width( ui_main_imgbutton_imgbutton3, LV_SIZE_CONTENT);  /// 32
lv_obj_set_x( ui_main_imgbutton_imgbutton3, 795 );
lv_obj_set_y( ui_main_imgbutton_imgbutton3, 673 );

ui_main_label_label4 = lv_label_create(ui_main);
lv_obj_set_width( ui_main_label_label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_label_label4, 830 );
lv_obj_set_y( ui_main_label_label4, 675 );
lv_label_set_text(ui_main_label_label4,"Exit");
lv_obj_set_style_text_font(ui_main_label_label4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_imgbutton_imgbutton1 = lv_imagebutton_create(ui_main);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_dark_theme_a_button_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton1, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton1, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton1, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton1, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton1, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_main_imgbutton_imgbutton1, 32);
lv_obj_set_width( ui_main_imgbutton_imgbutton1, LV_SIZE_CONTENT);  /// 32
lv_obj_set_x( ui_main_imgbutton_imgbutton1, 890 );
lv_obj_set_y( ui_main_imgbutton_imgbutton1, 673 );

ui_main_label_label3 = lv_label_create(ui_main);
lv_obj_set_width( ui_main_label_label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_label_label3, 930 );
lv_obj_set_y( ui_main_label_label3, 676 );
lv_label_set_text(ui_main_label_label3,"Info");
lv_obj_set_style_text_font(ui_main_label_label3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_imgbutton_imgbutton2 = lv_imagebutton_create(ui_main);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_dark_theme_b_button_png, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton2, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton2, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton2, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_main_imgbutton_imgbutton2, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_main_imgbutton_imgbutton2, 32);
lv_obj_set_width( ui_main_imgbutton_imgbutton2, LV_SIZE_CONTENT);  /// 32
lv_obj_set_x( ui_main_imgbutton_imgbutton2, 990 );
lv_obj_set_y( ui_main_imgbutton_imgbutton2, 673 );

ui_main_label_label2 = lv_label_create(ui_main);
lv_obj_set_width( ui_main_label_label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_label_label2, 1030 );
lv_obj_set_y( ui_main_label_label2, 675 );
lv_label_set_text(ui_main_label_label2,"Install");
lv_obj_set_style_text_font(ui_main_label_label2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_label_label1 = lv_label_create(ui_main);
lv_obj_set_width( ui_main_label_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_main_label_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_main_label_label1, 550 );
lv_obj_set_y( ui_main_label_label1, 330 );
lv_obj_set_align( ui_main_label_label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_main_label_label1,"12:00");
lv_obj_set_style_text_font(ui_main_label_label1, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_main_button_button6, ui_event_main_button_button6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_main_button_button4, ui_event_main_button_button4, LV_EVENT_ALL, NULL);

}
