// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_screen2_screen_init(void)
{
ui_screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_screen2_arc_arc1 = lv_arc_create(ui_screen2);
lv_obj_set_width( ui_screen2_arc_arc1, 150);
lv_obj_set_height( ui_screen2_arc_arc1, 150);
lv_obj_set_x( ui_screen2_arc_arc1, -522 );
lv_obj_set_y( ui_screen2_arc_arc1, -253 );
lv_obj_set_align( ui_screen2_arc_arc1, LV_ALIGN_CENTER );
lv_arc_set_value(ui_screen2_arc_arc1, 50);


ui_screen2_button_button3 = lv_button_create(ui_screen2);
lv_obj_set_width( ui_screen2_button_button3, 100);
lv_obj_set_height( ui_screen2_button_button3, 50);
lv_obj_set_x( ui_screen2_button_button3, -335 );
lv_obj_set_y( ui_screen2_button_button3, -299 );
lv_obj_set_align( ui_screen2_button_button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_screen2_button_button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_screen2_button_button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_screen2_label_label8 = lv_label_create(ui_screen2);
lv_obj_set_width( ui_screen2_label_label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_screen2_label_label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_screen2_label_label8, -227 );
lv_obj_set_y( ui_screen2_label_label8, -313 );
lv_obj_set_align( ui_screen2_label_label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_screen2_label_label8,"text");

ui_screen2_calendar_calendar1 = lv_calendar_create(ui_screen2);
lv_obj_t *ui_screen2_calendar_calendar1_header = lv_calendar_header_arrow_create(ui_screen2_calendar_calendar1);
lv_obj_set_width( ui_screen2_calendar_calendar1, 230);
lv_obj_set_height( ui_screen2_calendar_calendar1, 240);
lv_obj_set_x( ui_screen2_calendar_calendar1, -489 );
lv_obj_set_y( ui_screen2_calendar_calendar1, -3 );
lv_obj_set_align( ui_screen2_calendar_calendar1, LV_ALIGN_CENTER );

ui_screen2_checkbox_checkbox1 = lv_checkbox_create(ui_screen2);
lv_checkbox_set_text(ui_screen2_checkbox_checkbox1,"Checkbox");
lv_obj_set_width( ui_screen2_checkbox_checkbox1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_screen2_checkbox_checkbox1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_screen2_checkbox_checkbox1, -202 );
lv_obj_set_y( ui_screen2_checkbox_checkbox1, -273 );
lv_obj_set_align( ui_screen2_checkbox_checkbox1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_screen2_checkbox_checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_screen2_dropdown_dropdown1 = lv_dropdown_create(ui_screen2);
lv_dropdown_set_options( ui_screen2_dropdown_dropdown1, "Option 1\nOption 2\nOption 3" );
lv_obj_set_width( ui_screen2_dropdown_dropdown1, 150);
lv_obj_set_height( ui_screen2_dropdown_dropdown1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_screen2_dropdown_dropdown1, -186 );
lv_obj_set_y( ui_screen2_dropdown_dropdown1, -199 );
lv_obj_set_align( ui_screen2_dropdown_dropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_screen2_dropdown_dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_screen2_keyboard_keyboard1 = lv_keyboard_create(ui_screen2);
lv_obj_set_width( ui_screen2_keyboard_keyboard1, 300);
lv_obj_set_height( ui_screen2_keyboard_keyboard1, 120);
lv_obj_set_x( ui_screen2_keyboard_keyboard1, -413 );
lv_obj_set_y( ui_screen2_keyboard_keyboard1, 208 );
lv_obj_set_align( ui_screen2_keyboard_keyboard1, LV_ALIGN_CENTER );

ui_screen2_slider_slider1 = lv_slider_create(ui_screen2);
lv_slider_set_value( ui_screen2_slider_slider1, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_screen2_slider_slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_screen2_slider_slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_screen2_slider_slider1, 150);
lv_obj_set_height( ui_screen2_slider_slider1, 10);
lv_obj_set_x( ui_screen2_slider_slider1, -200 );
lv_obj_set_y( ui_screen2_slider_slider1, -118 );
lv_obj_set_align( ui_screen2_slider_slider1, LV_ALIGN_CENTER );


//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_screen2_slider_slider1,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_screen2_slider_slider1, lv_obj_get_style_pad_right(ui_screen2_slider_slider1,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_screen2_spinbox_spinbox1 = lv_spinbox_create(ui_screen2);
lv_obj_set_width( ui_screen2_spinbox_spinbox1, 70);
lv_obj_set_height( ui_screen2_spinbox_spinbox1, 42);
lv_obj_set_x( ui_screen2_spinbox_spinbox1, -230 );
lv_obj_set_y( ui_screen2_spinbox_spinbox1, -36 );
lv_obj_set_align( ui_screen2_spinbox_spinbox1, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_screen2_spinbox_spinbox1, 4, 2);
lv_spinbox_set_range( ui_screen2_spinbox_spinbox1, 0,9999 );
lv_spinbox_set_cursor_pos(ui_screen2_spinbox_spinbox1, 1 - 1);

ui_screen2_switch_switch1 = lv_switch_create(ui_screen2);
lv_obj_set_width( ui_screen2_switch_switch1, 50);
lv_obj_set_height( ui_screen2_switch_switch1, 25);
lv_obj_set_x( ui_screen2_switch_switch1, -229 );
lv_obj_set_y( ui_screen2_switch_switch1, 43 );
lv_obj_set_align( ui_screen2_switch_switch1, LV_ALIGN_CENTER );


ui_screen2_bar_bar2 = lv_bar_create(ui_screen2);
lv_bar_set_value(ui_screen2_bar_bar2,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_screen2_bar_bar2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_screen2_bar_bar2, 150);
lv_obj_set_height( ui_screen2_bar_bar2, 10);
lv_obj_set_align( ui_screen2_bar_bar2, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_screen2_bar_bar2,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_screen2_bar_bar2, lv_obj_get_style_pad_right(ui_screen2_bar_bar2,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_screen2_chart_chart1 = lv_chart_create(ui_screen2);
lv_obj_set_width( ui_screen2_chart_chart1, 403);
lv_obj_set_height( ui_screen2_chart_chart1, 300);
lv_obj_set_x( ui_screen2_chart_chart1, 363 );
lv_obj_set_y( ui_screen2_chart_chart1, -182 );
lv_obj_set_align( ui_screen2_chart_chart1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_screen2_chart_chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_screen2_chart_chart1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_screen2_chart_chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_screen2_chart_chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_screen2_chart_chart1, LV_CHART_TYPE_LINE);

ui_screen2_chart_chart1_Xaxis = lv_scale_create( ui_screen2_chart_chart1 );
lv_scale_set_mode( ui_screen2_chart_chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_screen2_chart_chart1_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_screen2_chart_chart1_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_screen2_chart_chart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_screen2_chart_chart1,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_screen2_chart_chart1,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_screen2_chart_chart1_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_screen2_chart_chart1_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_screen2_chart_chart1_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_screen2_chart_chart1_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_screen2_chart_chart1_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_screen2_chart_chart1_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_screen2_chart_chart1_Xaxis, (5>0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_screen2_chart_chart1_Xaxis, 2 >= 1 ? 2 : 1 );
ui_screen2_chart_chart1_Yaxis1 = lv_scale_create( ui_screen2_chart_chart1 );
lv_scale_set_mode( ui_screen2_chart_chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_screen2_chart_chart1_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_screen2_chart_chart1_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_screen2_chart_chart1_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_screen2_chart_chart1,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_screen2_chart_chart1,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_screen2_chart_chart1_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_screen2_chart_chart1_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_screen2_chart_chart1_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_screen2_chart_chart1_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_screen2_chart_chart1_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_screen2_chart_chart1_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_screen2_chart_chart1_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_screen2_chart_chart1_Yaxis2 = lv_scale_create( ui_screen2_chart_chart1 );
lv_scale_set_mode( ui_screen2_chart_chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_screen2_chart_chart1_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_screen2_chart_chart1_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_screen2_chart_chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_screen2_chart_chart1,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_screen2_chart_chart1,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_screen2_chart_chart1_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_screen2_chart_chart1_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_screen2_chart_chart1_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_screen2_chart_chart1_Yaxis2, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_screen2_chart_chart1_Yaxis2, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_screen2_chart_chart1_Yaxis2, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_screen2_chart_chart1_Yaxis2, 2 >= 1 ? 2 : 1 );
lv_chart_series_t* ui_screen2_chart_chart1_series_1 = lv_chart_add_series(ui_screen2_chart_chart1, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_screen2_chart_chart1_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_screen2_chart_chart1, ui_screen2_chart_chart1_series_1, ui_screen2_chart_chart1_series_1_array);



//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_screen2_chart_chart1, LV_MAX3(50, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_screen2_chart_chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_screen2_spinner_spinner1 = lv_spinner_create(ui_screen2);
//lv_spinner_set_anim_params(ui_screen2_spinner_spinner1, 1000, 90);
lv_obj_set_width( ui_screen2_spinner_spinner1, 80);
lv_obj_set_height( ui_screen2_spinner_spinner1, 80);
lv_obj_set_x( ui_screen2_spinner_spinner1, 2 );
lv_obj_set_y( ui_screen2_spinner_spinner1, -204 );
lv_obj_set_align( ui_screen2_spinner_spinner1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_screen2_spinner_spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_screen2_tabview_tabview1 = lv_tabview_create(ui_screen2);
lv_tabview_set_tab_bar_size(ui_screen2_tabview_tabview1,50);
lv_obj_set_width( ui_screen2_tabview_tabview1, 321);
lv_obj_set_height( ui_screen2_tabview_tabview1, 200);
lv_obj_set_x( ui_screen2_tabview_tabview1, -34 );
lv_obj_set_y( ui_screen2_tabview_tabview1, 185 );
lv_obj_set_align( ui_screen2_tabview_tabview1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_screen2_tabview_tabview1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen2_tabview_tabview1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen2_tabview_tabview1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_screen2_tabpage_tabpage1 = lv_tabview_add_tab(ui_screen2_tabview_tabview1, "Title 1");

ui_screen2_tabpage_tabpage2 = lv_tabview_add_tab(ui_screen2_tabview_tabview1, "Title 2");

ui_screen2_tabpage_tabpage3 = lv_tabview_add_tab(ui_screen2_tabview_tabview1, "Title 3");

ui_screen2_textarea_textarea1 = lv_textarea_create(ui_screen2);
lv_obj_set_width( ui_screen2_textarea_textarea1, 356);
lv_obj_set_height( ui_screen2_textarea_textarea1, 202);
lv_obj_set_x( ui_screen2_textarea_textarea1, 385 );
lv_obj_set_y( ui_screen2_textarea_textarea1, 177 );
lv_obj_set_align( ui_screen2_textarea_textarea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_screen2_textarea_textarea1,"Placeholder...");



}
