// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_main
void ui_main_screen_init(void);
extern lv_obj_t *ui_main;
extern lv_obj_t *ui_main_panel_panel1;
extern lv_obj_t *ui_main_imgbutton_imgbutton4;
extern lv_obj_t *ui_main_imgbutton_imgbutton5;
extern lv_obj_t *ui_main_imgbutton_imgbutton6;
extern lv_obj_t *ui_main_imgbutton_imgbutton7;
extern lv_obj_t *ui_main_imgbutton_imgbutton8;
extern lv_obj_t *ui_main_imgbutton_imgbutton9;
extern lv_obj_t *ui_main_imgbutton_imgbutton10;
extern lv_obj_t *ui_main_imgbutton_imgbutton11;
extern lv_obj_t *ui_main_imgbutton_imgbutton12;
extern lv_obj_t *ui_main_imgbutton_imgbutton13;
extern lv_obj_t *ui_main_imgbutton_imgbutton14;
extern lv_obj_t *ui_main_imgbutton_imgbutton15;
extern lv_obj_t *ui_main_imgbutton_imgbutton16;
extern lv_obj_t *ui_main_imgbutton_imgbutton17;
extern lv_obj_t *ui_main_imgbutton_imgbutton18;
extern lv_obj_t *ui_main_imgbutton_imgbutton19;
extern lv_obj_t *ui_main_panel_bottomline;
extern lv_obj_t *ui_main_imgbutton_imgbutton3;
extern lv_obj_t *ui_main_label_label4;
extern lv_obj_t *ui_main_imgbutton_imgbutton1;
extern lv_obj_t *ui_main_label_label3;
extern lv_obj_t *ui_main_imgbutton_imgbutton2;
extern lv_obj_t *ui_main_label_label2;
extern lv_obj_t *ui_main_label_label1;
extern lv_obj_t *ui_main_panel_panelpopup;
extern lv_obj_t *ui_main_label_label12;
void ui_event_main_button_button6( lv_event_t * e);
extern lv_obj_t *ui_main_button_button6;
extern lv_obj_t *ui_main_label_label9;
void ui_event_main_button_button4( lv_event_t * e);
extern lv_obj_t *ui_main_button_button4;
extern lv_obj_t *ui_main_label_label10;
// SCREEN: ui_screen2
void ui_screen2_screen_init(void);
extern lv_obj_t *ui_screen2;
extern lv_obj_t *ui_screen2_arc_arc1;
extern lv_obj_t *ui_screen2_button_button3;
extern lv_obj_t *ui_screen2_label_label8;
extern lv_obj_t *ui_screen2_calendar_calendar1;
extern lv_obj_t *ui_screen2_checkbox_checkbox1;
extern lv_obj_t *ui_screen2_dropdown_dropdown1;
extern lv_obj_t *ui_screen2_keyboard_keyboard1;
extern lv_obj_t *ui_screen2_slider_slider1;
extern lv_obj_t *ui_screen2_spinbox_spinbox1;
extern lv_obj_t *ui_screen2_switch_switch1;
extern lv_obj_t *ui_screen2_bar_bar2;
extern lv_obj_t *ui_screen2_chart_chart1;
extern lv_obj_t *ui_screen2_chart_chart1_Xaxis;
extern lv_obj_t *ui_screen2_chart_chart1_Yaxis1;
extern lv_obj_t *ui_screen2_chart_chart1_Yaxis2;
extern lv_obj_t *ui_screen2_spinner_spinner1;
extern lv_obj_t *ui_screen2_tabview_tabview1;
extern lv_obj_t *ui_screen2_tabpage_tabpage1;
extern lv_obj_t *ui_screen2_tabpage_tabpage2;
extern lv_obj_t *ui_screen2_tabpage_tabpage3;
extern lv_obj_t *ui_screen2_textarea_textarea1;
extern lv_obj_t *ui_startevents____initial_actions0;

LV_IMG_DECLARE( ui__temporary_image );
LV_IMG_DECLARE( ui_img_29c1ff1b697b468082d43540425fca8f538865a8d1f876de46ae5490203b6c2e_png);   // assets/29c1ff1b697b468082d43540425fca8f538865a8d1f876de46ae5490203b6c2e.png
LV_IMG_DECLARE( ui_img_30e1e5aed207066f1b8acb2c7d2a3e532b3d8707615c58e40635bc5d84377ce3_png);   // assets/30e1e5aed207066f1b8acb2c7d2a3e532b3d8707615c58e40635bc5d84377ce3.png
LV_IMG_DECLARE( ui_img_399bd3a4f656457bb63e921378eb701908298c8f2b2ad3193c437c206da97681_png);   // assets/399bd3a4f656457bb63e921378eb701908298c8f2b2ad3193c437c206da97681.png
LV_IMG_DECLARE( ui_img_3c3011e367e82258bbd36283bfe89d7292e6f44792bda005da3b964cd6388013_png);   // assets/3c3011e367e82258bbd36283bfe89d7292e6f44792bda005da3b964cd6388013.png
LV_IMG_DECLARE( ui_img_4b53da7ca4b118fe37c8b8040609b84dc63214d6131c51592486de9bf29ef29c_png);   // assets/4b53da7ca4b118fe37c8b8040609b84dc63214d6131c51592486de9bf29ef29c.png
LV_IMG_DECLARE( ui_img_4ffe57aabf1b6a2bf19cab0139a8bb4f99d14ef2f0031f83acd0f28810f66dbf_png);   // assets/4ffe57aabf1b6a2bf19cab0139a8bb4f99d14ef2f0031f83acd0f28810f66dbf.png
LV_IMG_DECLARE( ui_img_628f3436b87a02061bf9014ee7949fc379564c75364e66dca290fb1e54e9c095_png);   // assets/628f3436b87a02061bf9014ee7949fc379564c75364e66dca290fb1e54e9c095.png
LV_IMG_DECLARE( ui_img_66b639f88213ebf50af4a9eaca2da8c64a24a7314a0c80d587fec466df74d8b9_png);   // assets/66b639f88213ebf50af4a9eaca2da8c64a24a7314a0c80d587fec466df74d8b9.png
LV_IMG_DECLARE( ui_img_7f4d41bf9dbc8f7379e2f7530b8e969220dfdc933506ec8eaab7085267533a50_png);   // assets/7f4d41bf9dbc8f7379e2f7530b8e969220dfdc933506ec8eaab7085267533a50.png
LV_IMG_DECLARE( ui_img_9743b1bb18f8b7e40947a037557131be402985046b4e57f7c2c4796abe024b30_png);   // assets/9743b1bb18f8b7e40947a037557131be402985046b4e57f7c2c4796abe024b30.png
LV_IMG_DECLARE( ui_img_ad4d31f664a1ce704f0219da2805f8459595bc3c01c3f04df2e32ba34a05b8c6_png);   // assets/ad4d31f664a1ce704f0219da2805f8459595bc3c01c3f04df2e32ba34a05b8c6.png
LV_IMG_DECLARE( ui_img_aeab72bcb6fb6c79c32bddec987764f6e47c3e90cd32642a84de75f631b4eed0_png);   // assets/aeab72bcb6fb6c79c32bddec987764f6e47c3e90cd32642a84de75f631b4eed0.png
LV_IMG_DECLARE( ui_img_b7c8b605f109a0f090fd4231a33c87eaf91ff1bb3a1b6fe94b9057a822162a6d_png);   // assets/b7c8b605f109a0f090fd4231a33c87eaf91ff1bb3a1b6fe94b9057a822162a6d.png
LV_IMG_DECLARE( ui_img_bfeb5333a4473854d4cba8332d64152d595879c3714e687b45c47ad33b234a08_png);   // assets/bfeb5333a4473854d4cba8332d64152d595879c3714e687b45c47ad33b234a08.png
LV_IMG_DECLARE( ui_img_d3c210e61e8487200fc4c344987243a60257838187a69a6a81c42d7447d5d192_png);   // assets/d3c210e61e8487200fc4c344987243a60257838187a69a6a81c42d7447d5d192.png
LV_IMG_DECLARE( ui_img_f9dc003e469d3986eb0f7b6d972629ef201946028d530ac946823886e22ca3b2_png);   // assets/f9dc003e469d3986eb0f7b6d972629ef201946028d530ac946823886e22ca3b2.png
LV_IMG_DECLARE( ui_img_dark_theme_plus_button_png);   // assets/Dark theme/Plus_Button.png
LV_IMG_DECLARE( ui_img_dark_theme_a_button_png);   // assets/Dark theme/A_Button.png
LV_IMG_DECLARE( ui_img_dark_theme_b_button_png);   // assets/Dark theme/B_Button.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
