// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void yesAcction(lv_event_t * e)
{
	lv_obj_add_flag(ui_screen1_panel_panelpopup, LV_OBJ_FLAG_HIDDEN);
}

void noAcction(lv_event_t * e)
{
	lv_obj_add_flag(ui_screen1_panel_panelpopup, LV_OBJ_FLAG_HIDDEN);
}
